import "%modules%/header/header";
import "%modules%/promo/promo";
import "%modules%/advantage/advantage";
import "%modules%/reviews/reviews";
import "%modules%/services/services";
import "%modules%/technology/technology";
import "%modules%/menu/menu";
import "%modules%/menu/service-catalog/service-catalog";
import "%modules%/making-appointment/making-appointment";